-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 13:43:33 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`товары`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`товары` (
  `id_товара` INT NOT NULL AUTO_INCREMENT,
  `название` VARCHAR(45) NOT NULL,
  `артикул` VARCHAR(6) NOT NULL,
  `категория` INT NOT NULL,
  `ед_изм` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_товара`),
  UNIQUE INDEX `артикул_UNIQUE` (`артикул` ASC) VISIBLE,
  UNIQUE INDEX `id_товара_UNIQUE` (`id_товара` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`складские_ячейки`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`складские_ячейки` (
  `id_ячейки` INT NOT NULL AUTO_INCREMENT,
  `номер` VARCHAR(4) NOT NULL,
  `зона` INT NOT NULL,
  `id_товара` INT NOT NULL,
  `текущее_количество` INT NOT NULL,
  PRIMARY KEY (`id_ячейки`),
  UNIQUE INDEX `id_ячейки_UNIQUE` (`id_ячейки` ASC) VISIBLE,
  CONSTRAINT `товар`
    FOREIGN KEY (`id_товара`)
    REFERENCES `mydb`.`товары` (`id_товара`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`поставщики`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`поставщики` (
  `id_поставщика` INT NOT NULL AUTO_INCREMENT,
  `название` VARCHAR(45) NOT NULL,
  `инн` INT NOT NULL,
  `телефон` INT NOT NULL,
  `адрес` INT NOT NULL,
  `контактное_лицо` INT NOT NULL,
  PRIMARY KEY (`id_поставщика`),
  UNIQUE INDEX `id_поставщика_UNIQUE` (`id_поставщика` ASC) VISIBLE,
  UNIQUE INDEX `инн_UNIQUE` (`инн` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`поступления`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`поступления` (
  `id_поступления` INT NOT NULL AUTO_INCREMENT,
  `дата` DATE NOT NULL,
  `id_поставщика` INT NOT NULL,
  `id_товара` INT NOT NULL,
  `количество` INT NOT NULL,
  `цена_закупки` INT NOT NULL,
  PRIMARY KEY (`id_поступления`),
  UNIQUE INDEX `id_поступления_UNIQUE` (`id_поступления` ASC) VISIBLE,
  CONSTRAINT `поставщик`
    FOREIGN KEY (`id_поставщика`)
    REFERENCES `mydb`.`поставщики` (`id_поставщика`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `товары`
    FOREIGN KEY (`id_товара`)
    REFERENCES `mydb`.`товары` (`id_товара`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`отгрузки`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`отгрузки` (
  `id_отгрузки` INT NOT NULL AUTO_INCREMENT,
  `дата` DATE NOT NULL,
  `id_товара` INT NOT NULL,
  `количество` INT NOT NULL,
  `покупатель` INT NOT NULL,
  PRIMARY KEY (`id_отгрузки`),
  UNIQUE INDEX `id_отгрузки_UNIQUE` (`id_отгрузки` ASC) VISIBLE,
  CONSTRAINT `товар2`
    FOREIGN KEY (`id_товара`)
    REFERENCES `mydb`.`товары` (`id_товара`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
